AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  audiobook-s2t-deepspeech
  - b)	HTTP API (ml-inference): Perform an inference using DeepSpeech on audio.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Parameters:
  AudioBucketName:
    Type: String
    Description: S3 bucket for audio
    Default: ab-283419117448-s2t-audio

Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 3008  # 4096, change once memory quota is upgraded: https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html#troubleshooting-deployment-quotas
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucketName
      Events:
        http:
          Type: Api
          Properties:
            Path: /deepspeech
            Method: POST
        warm:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Input: |
              { "isWarmerEvent": true }
    Metadata:
      DockerContext: ./ml-inference
      Dockerfile: Dockerfile
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InferenceApi:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deepspeech"
  InferenceFunction:
    Description: "InferenceFunction Function ARN"
    Value: !GetAtt InferenceFunction.Arn
